version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: language_user
      POSTGRES_PASSWORD: language_pass
      POSTGRES_DB: language_db
    ports:
      - '5434:5434'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
